{{- $imagePullSecret := .Values.imagePullSecret }}
{{- if not (empty $imagePullSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marklogic.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{%s:{"auth":"%s"}}}` ($imagePullSecret.registry | quote) (printf "%s:%s" $imagePullSecret.username $imagePullSecret.password | b64enc) | b64enc | quote }}
{{- end }}